# Generated by Django 4.1.3 on 2023-03-03 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_date_post_created_date_post_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='date',
        ),
    ]
